# Generated by Django 6.0.7 on 2026-09-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачено"),
                    ("paid", "Оплачено"),
                    ("no_payment_required", "Оплата не требуется"),
                ],
                default="unpaid",
                max_length=30,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID цены Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Открыта"),
                    ("complete", "Завершена"),
                    ("expired", "Истекла"),
                ],
                max_length=20,
                verbose_name="Статус сессии Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
